[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -109

[[main]]
  name = "Theory"
  identifier = "Theory"
  weight = -108

[[main]]
  name = "Gtk3"
  identifier = "Gtk3"
  weight = -108

[[main]]
  name = "Gtk4"
  identifier = "Gtk4"
  weight = -108

# Submenus are done this way: parent -> identifier
#[[main]]
#name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107